### ISSUE TITLE
Verify Possible Difference in Tokenization & Sentence Splitting

### ISSUE THREAD

**Issue by MadhukarSP** [juanmirocks/LocText#10]
- [x] Verify the differences between LocText java **tokenizer** vs. relna python's, if any
  - relna: **TmVarTokenizer** ⚠️ the parser uses another `' '.split` tokenizer, not entirely sure why yet. Both are indeed used -- **Must clarify**
  - LocText: **StanfordCoreNLP** See: [code](https://github.com/juanmirocks/LocText-old-ShrikantThesis/blob/1dc374fd50e8d6e874b196d104ecf41aa64aff87/LocText/src/main/java/com/xmlBuilder/sParser.java#L47)

---
- [x] Verify the differences between LocText java **sentence splitting** vs. relna python's, if any
  - relna: **NLTKSplitter**
  - LocText: **StanfordCoreNLP** See: [code](https://github.com/juanmirocks/LocText-old-ShrikantThesis/blob/1dc374fd50e8d6e874b196d104ecf41aa64aff87/LocText/src/main/java/com/xmlBuilder/sParser.java#L47)
 
---

* [x] 🔴 Bug-fix the fact that SpacyParser class uses another tokenizer
  * ➡️ Default to spacy's tokenizer if spacy parser is used -- otherwise default to nltktokenizer

* [x] Do not default to `TmVarTokenizer` in relations_pipeline as that doesn't make any sense for LocText, and not even relna
  * ➡️ Actually, in preliminary evaluations, `TmVarTokenizer` performed better (`F 0.6452`) vs SpacyTokenizer (through generic) (`F 0.63~`0

**Comment by juanmirocks** [comment]
Fixed: 72528ba9d50103b26191fe61d174084fcd590118

**Comment by juanmirocks** [comment]
So far the sentence splitter was not changed since I do not think this will pose any major difference in performance
