### ISSUE TITLE
Run original java code to check balance of pos. vs neg. instances

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#14]
* Python code to get balance of instances: https://github.com/juanmirocks/LocText/blob/develop/loctext/learning/train.py#L108
* [x] **Java code?**

**Comment by MadhukarSP** [comment]
Original Java Code (LocText-Shrikanth) - Positive vs Negative Instances data

SS Modal : Pos - 270 , Neg - 237 (TrainDev)

DS Modal : Pos - 79 , Neg - 1128 (TrainDev)
