### ISSUE TITLE
Profile code to speed it up 

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#17]
* [ ] Profile code to inspect top 20% routes/functions that take most of the running time
* [ ] Improve their efficiency

For example, currently the PorterStemmer class is created multiple times in different feature generators and called repeatedly to generate the stems instead of caching them.

**Comment by shpendm** [comment]
1. I propose using KCacheGrind via pyprof2calltree for the profiling part which is a graphical way of showing the results and much more detailed than command line ones. Basically, we do not have to intrude the code by, for example, adding cProfile or something similar. We just have to run these commands in the terminal (provided that KCacheGrind and PyProf2CallTree are installed):
$ sudo python3 -m cProfile -o loctext.cprof setup.py

$ pyprof2calltree -k -i loctext.cprof

2. About improving the efficiency, I need to ask you more about the internal code structure. What properties are to be cached?  Using memoize or lru_cache decorators, If there are used same arguments then it makes sense to use caching extensively, but if arguments are different then we need to decide more carefully. In case of different arguments, then partial caching would make sense (more troublesome)

**Comment by juanmirocks** [comment]
Seems good. Let's talk about it now

**Comment by juanmirocks** [comment]
Current speed is quite good -- Whole training takes around 25 seconds.

Could be even faster if we could persist the memory of the spacy parser and the always-regeneration of the same features.
