### ISSUE TITLE
‼️ Impl. Converter from STRING id to UniProt ID

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#19]
* String mapping: http://string-db.org/mapping_files/uniprot_mappings/

* [x] in docker file, download all dictionaries (for loop)
* [x] most_common_organisms = ... python dict
~~* [ ] lazy evaluation of the full_organisms_dictionary~~ we will not need for now. See comments https://github.com/juanmirocks/LocText/issues/19#issuecomment-267259590 and https://github.com/juanmirocks/LocText/issues/19#issuecomment-267263018
* [x] Implement tests (preferably in _pytest_)
* [x] Juanmi checks

**Comment by juanmirocks** [comment]
Other possible way of mapping (not necessary for us), as reported by Pandu, previous student:

> I joined the entries on entities.tsv and names.tsv from the Tagcorpus which was given to me by Lars. Do you still remember those files?

> Also, I just checked my thesis. It seems that my bachelor thesis is a very complete reference for this. Try to read sections 4.4.2. and 4.4.3. of my thesis and you would figure out how it was done in my thesis :)

**Comment by juanmirocks** [comment]
@shpendm status?

**Comment by juanmirocks** [comment]
@shpendm are the tests done?

**Comment by shpendm** [comment]
lazy evaluation of the full_organisms_dictionary -> larstagger only uses most_common_organisms

**Comment by juanmirocks** [comment]
@shpendm then, can you narrow down these common organisms? What are their names?

**Comment by shpendm** [comment]
Names of the common organisms are:
Human, Mouse,Arabidopsis thaliana, Schizosaccharomyces pombe, Saccharomyces cerevisiae, [Escherichia coli str. K-12 substr. MG1655], Ligularia, Caenorhabditis elegans, Drosophila melanogaster, Danio rerio, 
Basically, those that are included here:
http://string-db.org/mapping_files/uniprot_mappings/   (except full_uniprot_2_string.04_2015.tsv.gz)

**Comment by juanmirocks** [comment]
@shpendm awesome, sounds good and sufficient. Let's leave it like this. Good job.
