### ISSUE TITLE
‼️ Put normalizations written in PubAnnotation format back to tagtog

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#2]
The current "final" corpus is written in PubAnnotation format: https://www.tagtog.net/-corpora/-dl/loctext/pubannotation

Tasks:

* [x] Write the UniProt ID (SwissProt), Taxonomy ID, and GO id to corpus: https://github.com/juanmirocks/LocText/tree/develop/resources/corpora/LocText -- just write in json. Map ids for normalizations (see `loctext/util/__init__.py`)
  * `n_7`: UniProt
  * `n_8`: GO
  * `n_9`: Taxonomy

* [x] verify and merge

  * [x] ‼️ error: there are some empty normalizations. For example, [in this pubannotation document](http://pubannotation.org/docs/sourcedb/PubMed/sourceid/12023506/annotations/visualize?projects=LocText) all entities normalizations are present. However, the corresponding new annjson file has empty normalization (`{}`) for the entities `PGF(2alpha) == uniprot:P43088`

  * [x] `py.test -v -s tests/test_loctext_pubannotation_to_annjson_conversion.py` must be all green 💚 (branch: `feature/careful_merge_of_2` -- your script is in `LocText/resources/corpora/LocText/annotation_reader.py`, which I changed only slightly)

  * [x] Fix bug: _there are few uniprot normalizations to Trembl (ids prefixed by `TR-`)_; The Pubannotation has **5** of those, whereas the new annjsons have only **2**. These numbers should be the same. See:

```
LocText_PubAnnotation_with_normalizations/PubMed-15342390.json:TR-Q92755
LocText_PubAnnotation_with_normalizations/PubMed-16731587.json:TR-M4NBC2
TR-M4NBC2
TR-M4NBC2
LocText_PubAnnotation_with_normalizations/PubMed-9346891.json:TR-Q9LMQ2
LocText_annjson_with_normalizations/apR4tcyiJeOQUQKqEhe_LAUHRAYq-15342390.ann.json:TR-Q92755
LocText_annjson_with_normalizations/awe78w2CkNjEZ6jslpcH3TMmYptu-16731587.ann.json:TR-M4NBC2
```

* [x] read normalizations in `annotation_readers.py` (nalaf)

```
UNIPROT_NORM_ID = 'n_7'
GO_NORM_ID = 'n_8'
TAXONOMY_NORM_ID = 'n_9'
```

Info:

* ann.json (tagtog) format: https://github.com/tagtog/tagtog-doc/wiki/tagtog-document-formats

Json object to write for confidence, exactly as:

```json
      "confidence": {
        "state": "",
        "who": [
          "user:goldberg"
        ],
        "prob": 1
      }
```

**Comment by juanmirocks** [comment]
```
madhutime	[7:06 PM]  
THe code has been committed for extracting normalization info from PubMed corpora and add it to Loctext corpora.

[7:07]  
feature branch name : feature/2

[7:09]  
Script which does job is : resources/corpora/annotation_reader.py

[7:10]  
Output files are stored in "resources/corpora/output" directory
```

**Comment by juanmirocks** [comment]
**to verify**

**Comment by juanmirocks** [comment]
Comments on slack:


madhutime	[1:43 PM]  
Hi @juanmirocks : I was just working on the issue [normalization not  being updated correctly in final LocText document]. I need a small clarification on following thing.

PubMed:12023506

[1:44]  
In above PubMed Json file.

I found an entity with two uniprot id. It is as follows.

{
     "id": "T2",
     "span": {
       "begin": 21,
       "end": 55
     },
     "obj": "uniprot:Q9NSA0"
   },
   {
     "id": "T3",
     "span": {
       "begin": 21,
       "end": 55
     },
     "obj": "uniprot:Q9Y694"
   }

madhutime	[1:52 PM]  
begin and end are same for these 2 entities. But they have 2 uniprot ID's. Do you want me to updates both the uniprot ID's in LocText normalization corpus.

madhutime	[1:57 PM]  
@juanmirocks : I think it is an issue with PubMed corpus. If we remove one of the entity, then all the normalizations will be updates correctly.. Let me know what must be my next step. [Correct the corpus or add two UniProt ID's in LocText normalizations for that text.]

[2:00]  
1) Correcting the corpus: Is the clean and safe way. No code change required.
2) Update two uniprot ID's: Need to add bit more logic.

My suggestion: Go for first approach. Since a text cannot have two uniprot ID's. [ID's are unique].

[2:01]  
text: Means protein or sub-cellular component.

juanmirocks	[2:14 PM]  
good finding

[2:14]  
we do need both (or as many there are) normalizations — I forgot we did that

[2:15]  
yes, possibly, some entities may be normalized to multiple ids if for example they are very close / related proteins (orthologos) or if the annotators was a bit unsure

[2:15]  
all the normalizations should be added in the following way:

[2:15]  
1. only one entity is created (as it is done now)

[2:16]  
2. all the normalizations with same offset are collected and written in the ann.json such as: `Q9NSA0,Q9Y694` — that is, a comma-separated list of ids — the same if it happens for go terms or even taxonomy ids

[2:16]  
we need this

[2:16]  
is it clear?

[2:18]  
to be more exact, you must finally write in teh annjson sth like:

[2:18]  
```normalizations: {
   "n_7":{
       "source":{
           "name":"UniProt",
           "id":"Q9NSA0,Q9Y694",
           "url":null
       },
       "recName":null,
       "confidence":{
           "state":"",
           "who":[
             "ml:dpeker"
           ],
           "prob":0.8458
       }
   }
}
"""

[2:18]  
makes sense?

**Comment by juanmirocks** [comment]
@MadhukarSP this was the code written by Shrikant to convert the tagtog annjson and a .tsv file of normalizations done by Tanya to produce the final PubAnnotation json files:

https://github.com/juanmirocks/BLAH1-LocText-Submission

Maybe that code contained bugs. Not sure. However, it also happened before that Shrikant run the code originally with a draft version of the .tsv file that contained some TODO-unormalized entities, and that may also be the origin of the problem.

In any case, now to the best of my knowledge, [this normalization file](https://github.com/juanmirocks/BLAH1-LocText-Submission/blob/master/src/main/resources/interFile.tsv) is the last updated one and likely (hopefully) correct. As a matter of fact, it does contain normalizations for the file you mentioned `12429849`, so it does have more information than the pubannotation files.

So.... you perhaps you can just read the annotations off this .tsv file and see. It should be way simpler to parse. 

In this .tsv file, you can regard the normalization `Protein` as an empty normalization, that is `""` as you were doing before.

**Comment by MadhukarSP** [comment]
A new branch has been created [feature/loctext_normalized_using_tsv] to extract the normalization information from "interFile.tsv" file.

Files added in feature/loctext_normalized_using_tsv:
annotation_reader.py            - Extracts normalization info ['interFile_modified.tsv'] and adds to LocText
interFile.tsv                           - Original tsv file 
interFile_modified.tsv           - Modified tsv file. 

Modifications in interFile_modified.tsv file:
Original value                                                 -> New Value
GO:0005773olar membrane                          -> vacuolar membrane
peroxisome proliferator-activated receptor ? -> peroxisome proliferator-activated receptor γ
PPAR?                                                          -> PPARγ
C/EBP?                                                         -> C/EBPβ
AP-1 ? adaptin                                              -> AP-1 μ adaptin
AP-1 adaptin subunit                                    -> AP-1 µ adaptin subunit

File modified:
test_loctext_pubannotation_to_annjson_conversion.py

Current code, extracts the information from .tsv [not from .csv]. 

All test cases have passed.

**Comment by juanmirocks** [comment]
Fixed
