### ISSUE TITLE
‼️ 📚 Reading Material

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#21]
* Paper: [Linked annotations: a middle ground for manual curation of biomedical databases and text corpora](http://bmcproc.biomedcentral.com/articles/10.1186/1753-6561-9-S5-A4)
* Shrikant's Thesis: see in LocText old repo
* Ashish's Thesis: see in relna repo

**Comment by juanmirocks** [comment]
@MadhukarSP and @shpendm these materials are indeed important for you guys

**Comment by shpendm** [comment]
Finished reading and analyzing them!

**Comment by juanmirocks** [comment]
Moved info to wiki https://github.com/juanmirocks/LocText/wiki
