### ISSUE TITLE
‼️Prepare data for final manual evaluation

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#22]
* [Tanya-generated file, SwissProt GO localization annotations for human](https://rostlab.org/~goldberg/human_localization_all.tab) (human_localization_all.tab i.e. tsv)

* The PMIDs we are looking for are those prefixed by the evidence identifiers: `ECO:0000303`, `ECO:0000305`, and `ECO:0000269`. See:

```shell
grep -o "ECO:[0-9]*|PubMed" human_localization_all.tsv | sort | uniq -c | sort
 255 ECO:0000303|PubMed
 400 ECO:0000305|PubMed
15591 ECO:0000269|PubMed
```

* To be exact, the whole list of unique PMIDs can be generated with:

```
grep -o "ECO:[0-9]*|PubMed:[0-9]*" human_localization_all.tsv | grep -o "PubMed:[0-9]*" | sort | uniq
```

As of now, the total count is: `7144`

---

* [x] Prepare data (create dataset with set of PMIDs in list above)
* [x] Run whole model on the data and get the results in order to verify that everything it's working fine
* [x] Ask for PubMedID from Juanmi
---

@goldbergtatyana Tanya I would appreciate if we can discuss this on Wednesday and set a clear plan for evaluations.

 I will also talk on Wednesday with Burkhard to gather his input.

**--> Tanya well suggested to evaluate on all SwissProt Human proteins**

**Comment by juanmirocks** [comment]
_test slack integration_

**Comment by shpendm** [comment]
We think that we understood this task, but we need to know in advance the following conditions:
1. What is the batch or organisms that we have to use and is there a fixed number of documents (in batches) or we compare for everything?
2. How are the normalizations provided in swissProt? If we know this, then we can compare them with the results given from StringTagger and provide the accuracy.

**Comment by juanmirocks** [comment]
@shpendm @MadhukarSP I added the file that was generated by Tanya with the PMIDs we are looking for. See the comments

**Comment by juanmirocks** [comment]
See continuation in #32
