### ISSUE TITLE
‼️Create STRING tagger Docker with dics & uniprot ids mapping

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#23]
https://github.com/juanmirocks/STRING-tagger-server

* [x] tag types: `-22, 9606` and set `autodetect=True`
* [x] Test with other organisms and make sure that they do not produce 9606 (human)
* [x] Have tests that use POST with very long texts (like a pubmed's abstract text)
* [x] Have the mapping using: https://github.com/juanmirocks/LocText/issues/19
* [x] Allow user to specify desired ids to annotate
  * [x] Write tests so to make sure that at least works with:
    * `-22` (only)
    * `-22,7227`
    * `-22,7227,9606`
* [x] Allow user to specify (in addition to ids to annotate) set `autodetect` True or False (the default must be `True`.
  * [x] Write tests so to make sure that at least works with:
    * `-22,9606` AND `autodetect=False` -- This should ONLY annotate cell locations and HUMAN proteins. No more organisms. **Test this**
    * `-22,9606` AND (`autodetect=True` or `autodetect` left unspecified --> default to True) == That is, this is the current behavior. Just test that it still works.

* [x] Juanmi verifies

**Comment by shpendm** [comment]
There are some cases that tag genes to two different organisms types and cases where one gene have two ID's for the same type. Examples:

''' {"end":52,"entities":[{"id":"ENSP00000378699","type":9606},{"id":"ENSMUSP00000020099","type":10090}],"start":48}]} '''

and
''' {"end":63,"entities":[{"id":"YDR071C","type":4932},{"id":"SPAP8A3.09c.1","type":4896},{"id":"SPAC9.02c.1","type":4896}],"start":59} '''

Is this what is expected or not? This shouldn't cause problems in mapping itself, but maybe later in accuracy measurement off methods.

**Comment by juanmirocks** [comment]
This is a great finding @shpendm -- yes, certainly this information is very important to consider evaluations.

Can you investigate why this happens? 

More weird is the repetition for the same organism of two different ids. Can you investigate why this happens and what those ids mean? (look up in the STRING database)

**Comment by shpendm** [comment]
Yes I will look into it

**Comment by juanmirocks** [comment]
@shpendm when do you think you have the whole pipeline ready (ready to be
combined with the LocText method) ?

I definitely would like to have it ready by this Friday

**Comment by shpendm** [comment]
I am planning it the same. I want to work on it today and tomorrow and have a meeting on Friday to check the correctness/progress. Is this ok by you?

**Comment by juanmirocks** [comment]
Perfect. The meeting will have to be over skype but that's not a problem

**Comment by shpendm** [comment]
This clarifying normaliation ids, except for -3, -22, for our tasks anything else doesn't make sense (as far as I have checked). I don't understand what Lars have meant by slightly different.

**Comment by juanmirocks** [comment]
@shpendm thanks -- I just put a comment in the description regarding -3 and -22.

btw, at what time crazy hours are you working?

@shpendm please lets have the skype call **today**

**Comment by juanmirocks** [comment]
@shpendm  see Lars comments:


Lars Juhl Jensen to Juan
Show more
9:23 AM
Dear Juan,

Not quite that simple. With the latest tagger, there are two files to give you more power when extracting pairs. The first is used to specify types to *tag*. The second is used to specify pairs of types to extract relations for.

To *tag* something like entire Medline for cellular component and proteins of any species, you want to tag the types -22, 9606 and set autodetect to true. Tagging -3 is not the same as setting autodetect to true; autodetect relies on having -3 in the dictionary, but you will basically never want to tag -3. The reason why you want to explicitly always tag 9606 is that most papers about human genes will *not* explicitly mention that they look at human. So you have to have 9606 turned on explicitly and not rely on autodetect to guess that a document is about human.

If you want to *tag* only cellular component and proteins of Drosophila melanogaster, you need to specify -22 and 7227. You cannot use parent taxids to turn on an entire genus, you must specifically add the taxid of the STRING species that you want to tag. Also, you really should preselect documents about drosophila in this case; tagging drosophila gene names uncritically in entire Medline without checking if a paper is about drosophila is a very bad idea (that is why we use autodetect instead of just turning on all species).

If you want to do cooccurrence scoring, you need to specify also which pairs of types you want. In your case you would want -22 with 9606, -22 with 7227 etc. If you were making STRING, you'd want 9606 with 9606, 7227 with 7227 etc.

Regarding what is fair in the evaluation, it depends on what you evaluate on. If you are running globally on Medline or any other corpus where you do not know the species a priori, you will want to use the "any species" configuration. If you run on benchmark corpora that pertain to a certain species, e.g. your human SwissProt example, you obviously want to tell the tagger which species the documents are about and not use autodetect.

Regarding the multiple mappings, I agree with your strategy. If one of the mapping options is correct according to the benchmark, it should be counted as true. Also, beware that not all Ensembl-UniProt mappings will be 1:1 - the vast majority should be, but there are exceptions, so your code has to handle that.

Best,
Lars
…
 
Lars Juhl Jensen to Juan
Show more
9:25 AM
One thing I forgot to mention: it is also important that you use the groups file when tagging. It affects the handling of ambiguity.

BW

**Comment by shpendm** [comment]
ok let's have a skype/hangout call at around 6pm. I am checking the above remarks and will see how to apply them (especially the groups' part).

**Comment by juanmirocks** [comment]
More comments from Lars:

Thank you again very much Lars, you are a vast source of knowledge :-) I mean it.

It’s becoming much more clearer now:

If I want to annotate any species, set: tags=-22, 9606 and autodetect=true
If I want to, e.g. annotate only human, set: tags=-22, 9606 and autodetect=false
The file of pairs will be useful to compare the performance of your existing occurrence scoring with essentially the “scoring” of LocText.
I agree on all your points regarding what prior information on organisms should be given to the annotator for evaluations.
Regarding the groups:

For simplicity, should I just use your provided tagger_groups.tsv ? (http://download.jensenlab.org/tagger_dictionary.tar.gz)
If all my current assumptions are correct, if I may suggest, some of this information is not entirely clear in the tagger’s README. If you agree, I’m happy to make a pull request with a few clarifications and more examples.

Thank you again Lars.

…
 
Lars Juhl Jensen to Juan
Show more
12:01 PM
You are right :-)

Regarding groups file, you can only that if you use the command-line tagger. If you use the Python wrapper, you don't have that functionality, unfortunately. It is not a big deal - the groups file is used to help eliminate ambiguity. If you benchmark the way you suggested, having more ambiguous options left should not harm the performance metrics.

Best,
Lars

**Comment by juanmirocks** [comment]
**That is, we need to annotate: `-22, 9606` and set (in python wrapper call) `autodetect=True`**

**Comment by juanmirocks** [comment]
@shpendm let's not use the groups for the moment

It should be now very simple to proceed 

what else is needed?

**Comment by shpendm** [comment]
Nothing else. Everything is clear!

**Comment by juanmirocks** [comment]
@shpendm any news? POST tests ?

**Comment by shpendm** [comment]
updated according to requirements

**Comment by juanmirocks** [comment]
@shpendm great 👍
