### ISSUE TITLE
‼️Fill in missing normalizations in interFile_modified.tsv file

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#27]
Dear Tanya,

I’m getting much closer wrt LocText.

Only, I found that many documents (39 out of the total 100) had proteins without being normalized to UniProt ids. At first I thought it was only a few cases so I was ignoring it. But now I’m seeing that this is affecting performance quite considerably.

I manually checked a few documents and it seems that most proteins can indeed be normalized.

Would it be possible for you to please fill in the missing normalization ids?

You would simply do it in the attached file (interFile_modified). You can use the tagtog interface to help you read the documents: https://www.tagtog.net/jmcejuela/LocText/pool

The proteins that have no normalization in the .tsv have in the corresponding column NormalizedID only written “Protein”.

It’s possible to find the set of the pmids docs with:

`grep "Protein\s*Protein" interFile_modified.tsv  | grep -o "^[0-9]*\s" | sort | uniq`

In particular, on tagtog you can search a pmid by searching on top, e.g., `docid:10072396`

Will you be able please to do this?

The tasks to be completed as part of this issue

* [x] Use Tanya new document with Green and red ones.
* [x] Create new folder for new documents in resources.
* [x] new interFile_modified_by_Tanya.tsv
* [x] Change read corpus to new path.
* [x] Counter number of greens (newly normalized) in new tsv file
* [x] Assert that the number of normalizations in the new corpus is equal to the number of normalizations of the previous one + the number of greens — put that in the test file (edited)
  * `num_normalizations(LocText_annjson_with_normalizations_latest_5_feb_2017) = num_normalizations(LocText_annjson_with_normalizations) + green_rows_count`

* [x] Juanmi verifies

Necessary Information wrt to this task:
1) The folder name containing latest documents : LocText_annjson_with_normalizations_latest_5_feb_2017
2) The file name containing latest changes from Tanya: interFile_modified_by_Tanya
3) Latest code has been checked into git under: 8_StringTaggerUniprot branch.

**Comment by goldbergtatyana** [comment]
I am afraid that the normalization for the remaining proteins is not possible. I checked the fisrt 15 proteins. For them, this is the case. The normalization is not possible for example, because:
1) protein name is too generic (e.g. Ferrochelatase from arabidopsis, pmid: 9346891; the protein has different subforms and so its unclear which subform is meant here)
2) is not in swisspot (e.g. EDTA from pea, pmid: 9346891)

**Comment by goldbergtatyana** [comment]
proteins like "green fluorescent protein" or "GFP" we said in the rules wont be related to an organism. So, they stay unnormalized as well.

**Comment by goldbergtatyana** [comment]
it is also the case that proteins in an abstract dont have any relation to an organism => no normalization possible. Example: pmid 11038182

**Comment by juanmirocks** [comment]
@goldbergtatyana awesome, thanks for this!

I did check randomly two documents, and at first sight, they appeared to me that they indeed can be normalized.

Could you please share the exact list of 15 documents? So maybe I test the other a bit more thoroughly.

P.D.: good job hustling on Sunday

**Comment by goldbergtatyana** [comment]
[no_norm.xlsx](https://github.com/juanmirocks/LocText/files/659530/no_norm.xlsx)

**Comment by goldbergtatyana** [comment]
Now I'm through the whole list and here is what comes out of it. Red are marked all proteins for which there is no normalization can  be made. Yellow - normalization could in principle be made, but I need to know which mentions the coordinates match. Green - normalization was made.

[interFile_modified_tg_dec182016.xlsx](https://github.com/juanmirocks/LocText/files/659536/interFile_modified_tg_dec182016.xlsx)

**Comment by juanmirocks** [comment]
Awesome. I check the yellow tmrw. Good night darling

**Comment by juanmirocks** [comment]
Hi there,

* regarding the yellow ones, [here are the documents on tagtog](https://www.tagtog.net/jmcejuela/LocText/-search/origid%3A(12612081%20OR%2023150645)) -- Does that help ? Btw, the 👁‍🗨 view `ann.json` gives you the exact offsets
* Regarding the red cases, I still think many of them can be normalized. For example, check for "shugoshin" here: https://www.tagtog.net/jmcejuela/LocText/-search/origid:16541025/aoQHNi1futtx.DKoe.q6eXk5lDFS-16541025?p=0&i=0
   * shugoshin is explicitly related to human on the tagtog document
   * I find "shugoshin 1" and "sugoshin 2" on SwissProt -- Not exactly the same name, but I guess it would be safe to select "shugoshin 1" and therefore `Q5FBB7`: http://www.uniprot.org/uniprot/?query=shugoshin+taxonomy%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22&sort=score

**Comment by juanmirocks** [comment]
@goldbergtatyana Perhaps you can quickly skim over the [tagtog documents that have non normalized proteins](https://www.tagtog.net/jmcejuela/LocText/-search/origid%3A(10072396%20OR%2010207082%20OR%2010644992%20OR%2011038182%20OR%2011564863%20OR%2012167088%20OR%2012177201%20OR%2012482924%20OR%2012566991%20OR%2012612081%20OR%2012682047%20OR%2014562095%20OR%2015143214%20OR%2015342390%20OR%2015467828%20OR%2015572352%20OR%2015788404%20OR%2016455656%20OR%2016541025%20OR%2016731587%20OR%2016788062%20OR%2016874308%20OR%2017202255%20OR%2018082604%20OR%2018182439%20OR%2018769150%20OR%2019403692%20OR%2020023648%20OR%2020071603%20OR%2020124190%20OR%2020142502%20OR%2020427278%20OR%20205532%20OR%2021282530%20OR%2023150645%20OR%207689721%20OR%208846782%20OR%209346891%20OR%209613572))

Btw, you can use the shortcuts `[` and `]` to nagivate to previous and next documents, respectively, 😀

**Comment by juanmirocks** [comment]
Furthermore, other documents that really do not cite any organism, likely implicitly assume human.

Here for example, https://www.tagtog.net/jmcejuela/LocText/-search/origid:15342390/apR4tcyiJeOQUQKqEhe_LAUHRAYq-15342390?p=0&i=0

For instance, I guess that "CITED4" is this human protein: http://www.uniprot.org/uniprot/Q99MA0

**Comment by goldbergtatyana** [comment]
Now to CITED4: looked into the paper of that protein as well and paper talks about both human and mouse version of it. So, blindly assigning human to non-normalized proteins would be wrong in my opinion as well.

**Comment by goldbergtatyana** [comment]
The with yellow marked proteins have been normalized now and the newest version of the normalization file is attached. 
[interFile_modified_tg_jan052017.xlsx](https://github.com/juanmirocks/LocText/files/687103/interFile_modified_tg_jan052017.xlsx)

**Comment by juanmirocks** [comment]
Yes, I agree it's out of scope reading the full paper.

However, I think the protein can still be normalized to either one
arbitrary (since I assume they have high sequence similarity, then is
irrelevant for final comparison) or even better normalize to both,
separating the ids with commas.

**Comment by goldbergtatyana** [comment]
I disagree with this brute force normalization approach. What is the goal of everything? Why are we enforcing normalization this way that will certainly introduce errors?

**Comment by MadhukarSP** [comment]
Reference link : https://github.com/juanmirocks/LocText/blob/develop/resources/corpora/LocText/interFile_modified.tsv

Above link points to interFile_modified.tsv, as per this issue we are supposed to get the NormalizedID for Protein [Which are currently marked red]. 

These NormalizedID can also be filled, if we make use of StringTagger, by following below steps. 
1) We could send the Entity name as text and type as Human (In case we are assuming that the organism is Human) and receive the JSON response with corresponding Normalized StringID and Uniprot ID. 
2) With the Uniprot ID from the response, we fill the corresponding cells in the interFile_modified.tsv document.

**Comment by juanmirocks** [comment]
I let you know soon. Jsonld may suffice

**Comment by MadhukarSP** [comment]
The tasks to be completed:

1) Use Tanya new document with Green and red ones. 
2) Create new folder for new documents in resources.
3) new interFile_modified_by_Tanya.tsv
4) Change read corpus to new path.

**Comment by MadhukarSP** [comment]
Task complete. 

Necessary Information wrt to this task:

The folder name containing latest documents : LocText_annjson_with_normalizations_latest_5_feb_2017
The file name containing latest changes from Tanya: interFile_modified_by_Tanya
Latest code has been checked into git under: 8_StringTaggerUniprot branch.

**Comment by MadhukarSP** [comment]
For our records:

The xlsx file from Tanya had a minor mistake. One of the record which had Uniprot ID was replaced with string Protein. The record is below.

Original record was :
11502169  Sdh1p  Protein  *Q00711*  abs  786  791

In interFile_modified_tg_jan052017.xlsx file, the same record was set as below by mistake.
11502169  Sdh1p  Protein  *Protein*  abs  786  791

Hence we got wrong count of newly normalized proteins. [Green ones].

The new interFile_modified_by_Tanya.tsv file has been updates with correct value.

**Comment by shpendm** [comment]
We also created a helper file 'helper_for_tsv_and_xlsx.py', for the cases when we have to deal with:
1. Conversion of xlsx to tsv file
2. Creation of a new tsv file that contains only normalized rows
3. Finding of differences between two tsv files and occurrences of non-normalized rows in those files

The file is placed in: resources/corpora/Loctext/
This might be helpful for the future changes/additions of input files.

**Comment by MadhukarSP** [comment]
The new test file containing following assertion is in file *test_num_of_normalizations.py*.

"Assert that the number of normalizations in the new corpus is equal to the number of normalizations of the previous one + the number of greens — put that in the test file"
