### ISSUE TITLE
‼️Assess performance against PubMed documents

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#32]
Linked to #22 

* [x] Juanmi & Tanya manually assess the results and finds interesting cases for the paper

**Comment by juanmirocks** [comment]
Thanks @goldbergtatyana 

You can decide yourself the exact assessment experiment.

General idea:

1. we run our method on all SwissProt PMIDs
2. we automatically evaluate `tp` and `fn` against SwissProt annotations
4. we generate for you a ranked list of the seeming `fp` (they may be actually new correct annotations not in SwissProt) -- It will be ranked with the number of times we found that relationship and in which PMIDs
3. you check some `top-n` of those results (you decide `n`) and _manually_ check whether our predictions are actually correct

Furthermore, we could do the same, this time running our method on new experiments (last years publications) and then you check the `top-n` again. Probably, this is the most exciting stuff as very likely the info of new publications is not in SwissProt at all, yet.

Or, if you decide, you can also focus on some specific proteins that you think are of general interest and we may hit gold with. Like maybe important proteins where we don't lab-experimentally know yet where they are located in the cell.

As for when we send you the results, it could be as early as next week.

Is it clear? :-)

**Comment by juanmirocks** [comment]
Also Tanya, do you think that it will be easy (meaning fast) and it makes sense to compare LocText against LocTree ?

Most interesting to see would be if they can complement each other.

I only wanna do this assessment if we can execute fast.

**Comment by juanmirocks** [comment]
Prediction results on all the PMIDs listed by SwissProt for GO location annotations:

[SwissProt_relations.zip](https://github.com/juanmirocks/LocText/files/769424/SwissProt_relations.zip)

**Comment by juanmirocks** [comment]
Here slightly the same only trying to explicitly annotate human proteins (I guess slightly better results):

[9606_SwissProt_relations.zip](https://github.com/juanmirocks/LocText/files/770326/9606_SwissProt_relations.zip)

**Comment by juanmirocks** [comment]
Here results for latest discoveries (last year publications, 12k by searching on pubmed: `((human OR patient) AND (protein OR gene) AND (localization OR localize OR localized OR subcellular OR compartment)) AND ("2015"[Date - Publication] : "2017/01/01"[Date - Publication]) AND hasabstract[text]`)

[9606_NewDiscoveries_relations.zip](https://github.com/juanmirocks/LocText/files/770328/9606_NewDiscoveries_relations.zip)

**Comment by juanmirocks** [comment]
https://www.tagtog.net/jmcejuela/LocText/-settings

**Comment by goldbergtatyana** [comment]
here are my results for swiss-prot relations. i tried to add specific comments where i could not find a relation. checking swiss-prot for *FEW* localization terms from the doc, i could actually find them there (in swiss-prot).

[9606_SwissProt_relations_tg.xlsx](https://github.com/juanmirocks/LocText/files/772184/9606_SwissProt_relations_tg.xlsx)

**Comment by juanmirocks** [comment]
Great! Not too bad, that's a 65% success rate so far. I wonder if there is
a dummy mistake for all those cases you didn't find any protein or
localization mention. Otherwise it's kinda impossible to find any
relationship at all lol

**Comment by juanmirocks** [comment]
Otherwise it's almost a 100% Success rate. I check tmrw those possible
mistakes, thank you Tanya!

**Comment by goldbergtatyana** [comment]
and the second file. would be great @juanmirocks if you could check the problematic cases i found yourself as well.

[9606_NewDiscoveries_relations_tg.xlsx](https://github.com/juanmirocks/LocText/files/772556/9606_NewDiscoveries_relations_tg.xlsx)

**Comment by juanmirocks** [comment]
Backup of old curation results: 

[Old_LocText_results_against_Pubmed_9606_with_tanya_and_juanmi_curation.zip](https://github.com/juanmirocks/LocText/files/867689/Old_LocText_results_against_Pubmed_9606_with_tanya_and_juanmi_curation.zip)
