### ISSUE TITLE
‼️ Calculate ner - performance differences in LocText branches (develop, feature/speed_up_relation_pipeline)

### ISSUE THREAD

**Issue by MadhukarSP** [juanmirocks/LocText#38]
While calculating ner performance on following branches, we found differences and they are in corresponding text file.

The FALSE NEGATIVE (fn) and FALSE POSITIVE (fp) information details are in the attachment.
[fp_fn_develop.txt](https://github.com/juanmirocks/LocText/files/790677/fp_fn_develop.txt)
[fp_fn_feature_speed_up_relation_pipeline.txt](https://github.com/juanmirocks/LocText/files/790680/fp_fn_feature_speed_up_relation_pipeline.txt)

Case 1
LocText: develop
nalaf: feature/Keep_Exploration

Case 2
LocText: feature/speed_up_relation_pipeline
nalaf: feature/Keep_Exploration

**Comment by juanmirocks** [comment]
Thanks @MadhukarSP

**Comment by juanmirocks** [comment]
@MadhukarSP FYI it is to be expected (or rather I'm glad of the fact) that the latest branch has improved performance because I was tinkering the code a bit precisely to improve the localization results.

Good finding. This is very important stuff.

Please proceed with the subtask 2 of #37

**Comment by juanmirocks** [comment]
@MadhukarSP I don't understand the cases you put -- you repeat cases? (case 1, case 2, case 1, ...) 

Please put the exact commit hashes of git for nalaf and LocText for all the cases

**Comment by juanmirocks** [comment]
Done
