### ISSUE TITLE
‼️ Write STRINGTagger in python LocText code

### ISSUE THREAD

**Issue by juanmirocks** [juanmirocks/LocText#8]
(Note that this task #8 **depends on** #23 and #19)

* [x] Write class `STRINGTagger` in `annotators.py` in LocText. This class must inherit `Tagger` from nalaf.
* [x] For the types (`class_id`) you must use the constants defined in: https://github.com/juanmirocks/LocText/blob/develop/loctext/util/__init__.py#L3-L11
  * [x] You must write the normalizations in the Entity class as a python dictionary (see `data.py` in nalaf, class `Entity`) like:
 
```python
new `Entity(class_id=..., offset=..., text=..., norm={UNIPROT_NORM_ID: "P04637,P02340", STRING_NORM_ID: "xxx,yyy"}
```

* [x] at the end of your defined method `annotate`, call the function `dataset.validate_entity_offsets()` (to verify offsets & texts of entities are good)

* [x] Test the `STRINGTagger` in a separate LocText (_pytest_) file.
  * Note: the simplest way to have a stub dataset for testing is to use the `StringReader` (defined in `readers.py` in _nalaf_). This simply takes a string in the constructor and, once the its method `read` is called, the dataset object is generated.

* [x] The `STRINGTagger` must react appropriately if the docker server is not running or cannot be reached. That is, you must have an appropriate try/except clause to detect for possible exceptions on http calls (and similar). As a reaction, you must catch and raise the exception, yet with a meaningful message to the user. Something along the lines: "The docker STRING tagger REST server cannot be reached. For installation, please refer to [url to our repository of the string docker]"
  * [x] This must be tested too. That is, confirm first that the docker image is not running, and then confirm that you catch the exception with the text you wrote above

* [x] Have parameter in constructor called `send_whole_once` (`Boolean`) with no default parameter
* [x] If `send_whole_once is False`, keep your current behavior of iterating and iterating all the parts' texts
* [x] else:
   * [x] send the whole document's text `document.get_text()` to the Docker image
   * [x] read back all annotations and fill them into the individuals parts handling the offsets _properly_. You can in `document.get_text()` choose any separation string you want (as in "\n") in case that simplifies your life.

* [x] Handle the case where the uniprot normalization id is actually `null`

* [x] From the docker tagger you receive for uniprot ids examples like `P02340|P53_MOUSE` or `P48347|14310_ARATH`. You must extract and write the accession number only! That is, examples: `P02340` and `P48347`

* Implement tests:

  * [x] Test that with `send_whole_once is True` we get either the same amount or more tagged entities:
      * `assert num_annotated_entities(send_whole_once==False) <= num_annotated_entities(send_whole_once==True and doc.get_text(separation='\n')`
   * Test that the choice of the separation string does not matter (`\n` vs `\n\n`):
     * `assert num_annotated_entities(send_whole_once==True and doc.get_text(separation='\n') == num_annotated_entities(send_whole_once==True and doc.get_text(separation='\n\n')`
   We used space as separator between parts. Hence above condition does not holds good.
    * You can use the functions:
      * `corpus = read_corpus("LocText")`
      * `def num_annotated_entities(corpus): return len(list(corpus.predicted_entities()))`

* [x] Write empty string only if you have NONE normalization, examples:
  * [ID1,ID2,] --> `{UNIPROT_NORM_ID: "ID1,ID2", STRING_NORM_ID: "..."}`
  * [] -> `{UNIPROT_NORM_ID: "", STRING_NORM_ID: "..."}`

* [x] Annotate ALL THREE: protein, localization, organism [see ids constants](https://github.com/juanmirocks/LocText/blob/feature/8_StringTaggerUniprot/loctext/util/__init__.py)

* [x] Show to Juanmi

* [x] combine this tagger with `LocTextAnnotator` to create the final combined method

* [x] Write the class which uses Tagger and RelationExtractor. In the constructor, use ner_kw_args and re_kw_args as arguments for name entity recognition and relation extractor. Call annotate method using ner and re, use inside "def annotate(dataset)" method. Basically, use StringTagger to create entities (ner) and use RelationExtraction to get those entities and create relations (re).

* [x] Test_LocTextfull and Test_LocTextBaselineFull for testing the ultimately results, that is to do prediction and compare the methods. Inside the method initialize ner with StringTagger and re with Baseline. 

---

In the end, the idea is simple, and it’s just that we want to use the STRING tagger (Lars) as an (Entity) Tagger class as defined in nalaf and to readily use in python

Hence we use Docker to run STRING tagger to get entity details.

Thus, the python tagger that must be implemented, calls the Docker tagger with REST APIs, reads the results, and saves them in a dataset object (nalaf Parts, Entity, ... ) (edited)

And the REST APIs calls are as simple sending strings (text) to the Docker tagger to annotate, and then just read the json response, and understand those to fill in the part.predicted_annotations

Further, that python tagger has already as input dataset objects (without annotations), and therefore with all the parts’ texts to send to the Docker tagger for annotation

**Comment by juanmirocks** [comment]
Shpend 

Check out for example the code;

* GnormPlusTagger class in nalaf
* TmVarTagger class, in nala (I think)

**Comment by shpendm** [comment]
The task #8 looks complete to us. Just for the case of \n or \n\n, we didn't follow that approach since we had space as delimiter for splitting the parts. The rest of the code is working and  all the test cases (also for the num_annotated_entities) have passed.

**Comment by shpendm** [comment]
We use space separator instead o \n or \n\n
